version: '1'

networks:
  javaguru:

services:
  message-broker:
    networks: [javaguru]
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    networks: [javaguru]
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql-database-init:/docker-entrypoint-initdb.d
    ports:
      - "3000:3306"

  web:
    networks: [javaguru]
    container_name: insurance-calc-container
    image: insurance-calculator:1.0.3
    ports:
      - "8080:8080"
    depends_on:
      - db
      - message-broker
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  doc-generator:
     networks: [javaguru]
     container_name: doc-generator-container
     image: doc-generator:1.0.2
     volumes:
       - ./doc_generator_app/docs/proposals:/app/docs/proposals
     ports:
       - "8888:8888"
     depends_on:
       - message-broker
     labels:
       collect_logs_with_filebeat: "true"
       decode_log_event_to_json_object: "true"

  file-storage:
      networks: [javaguru]
      container_name: file-storage-container
      image: file-storage:1.0.0
      volumes:
        - ./file_storage_app/docs/pdf_file_storage:/app/docs/pdf_file_storage
      ports:
       - "8000:8080"
      depends_on:
       - doc-generator

  blacklist-app:
    networks: [javaguru]
    container_name: blacklist-container
    image: black-list:1.0.0
    ports:
      - "8081:8080"
    depends_on:
      - db
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  elasticsearch:
    networks: [javaguru]
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data

  logstash:
    networks: [javaguru]
    image: my-custom-logstash:1.0.2
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    networks: [javaguru]
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    networks: [javaguru]
    image: my-custom-filebeat:1.0.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./elk/filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: always
    depends_on:
      - logstash

  metricbeat:
    networks: [javaguru]
    image: my-custom-metricbeat:1.0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: always
    depends_on:
      - logstash